server:
  applicationConnectors:
    - type: https
      port: 8080
      keyStorePath: example.keystore
      keyStorePassword: example
      validateCerts: false
      validatePeers: false
      idleTimeout: 60s

jerseyClientConfiguration:
  timeout: 60000ms

logging:
  level: INFO

  loggers:
    org.eclipse.jetty.servlets: DEBUG