server:
  applicationConnectors:
    - type: http
      port: 8080
      idleTimeout: 60s

jerseyClientConfiguration:
  timeout: 60000ms

logging:
  level: INFO

  loggers:
    org.eclipse.jetty.servlets: DEBUG